### ISSUE TITLE
Provide a licence and a release tarball

### ISSUE THREAD

**Issue by wigust** [vividsnow/perl-live#1]
Hello @vividsnow,

Thank you for this program!

Could I ask you about including a LICENCE file in this Git repository? Maybe a GPL3+ would serve well for this, because most of Emacs related stuff is under GPL3+ licence. WDYT? Also a release tarball would be great. I want to publish this program to Guix[1] package collection.

[1] https://www.gnu.org/software/guix/

Oleg.

**Comment by vividsnow** [comment]
Hello, done
